### ISSUE TITLE
Can I obtain SNP rs ids using CHR:POS or CHR:POS_A1_A2 column? TIA

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [HimesGroup/snpsettest#2]

**Comment by jaehyunjoo** [comment]
No, that is beyond the scope of our package. RS ID assignment can be done with the dbSNP database. I remember that there are a couple of programs that could do it for you  (e.g., [ANNOVAR](https://annovar.openbioinformatics.org/en/latest/)).  Thanks!
